version: '2'

services:
  grobid:
      image: lfoppiano/grobid:0.5.5
      ports:
        - "8070:8070"
      environment:
        - JAVA_OPTS=-Xmx1g
      networks:
        - elk

  elasticsearch:
      build: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./elasticsearch/esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk

  web:
    build: ./web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - "./web:/app"
    networks:
      - elk
networks:
  elk:
volumes:
  esdata: