version: '2'

services:
  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    build:
      context: ./
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/src/app
      - /src/app/node_modules
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    networks:
      - elk

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  grobid:
      image: lfoppiano/grobid:0.5.5
      ports:
        - "8070:8070"
      environment:
        - JAVA_OPTS=-Xmx1g
      networks:
        - elk

  elasticsearch:
      build: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./elasticsearch/esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      environment:
        ES_JAVA_OPTS: "-Xmx8g -Xms8g"
      networks:
        - elk

  web:
    build: ./web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - "./web:/app"
    networks:
      - elk
networks:
  elk:
volumes:
  esdata: